version: "3"

services:
  app:
    env_file:
      - .env
    build:
      context: ./app
      dockerfile: Dockerfile
      args:
        - PORT=$PORT
        - ALLOW_IFRAME=$ALLOW_IFRAME
        - PUBLIC_ALLOW_THUMBNAIL_PROXY=$PUBLIC_ALLOW_THUMBNAIL_PROXY
    ports:
      - "3000:3000"
  proxy:
    build:
      context: ./packages/proxy-server/rust
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
