version: "3"

services:
  app:
    image: "snuffydev/beatbump:master"
    build:
      context: ./app
      dockerfile: Dockerfile
      args:
        - PORT=$PORT
    ports:
      - "443:${PORT}"
    environment:
      PORT: 3000
      ALLOW_IFRAME: true
      ALLOW_THUMBNAIL_PROXY: false
      VITE_DOMAIN: "beatbump.io"
      VITE_SITE_URL: "https://beatbump.io"
      VITE_DONATION_URL: "https://www.paypal.com/donate/?hosted_button_id=E6YRHKS2H2KP2"
    restart: unless-stopped
  proxy:
    build:
      context: ./packages/proxy-server/deno
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    restart: unless-stopped
