[package]
name = "bb-proxy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3.21"
hyper = { version = "0.14.20", features = ["full"] }
hyper-tls = "0.5.0"
regex = "1.6.0"
tokio = { version = "1.20.1", features = ["full"] }
url = "2.2.2"
openssl-sys = "*"
once_cell = "1.19.0"

[features]
# Force openssl-sys to staticly link in the openssl library. Necessary when
# cross compiling to x86_64-unknown-linux-musl.
vendored = ["openssl-sys/vendored"]

[build]
rustflags = ["-C", "link-arg=-fuse-ld=lld"]

[profile.dev]
incremental = true
strip = false
lto = false
opt-level = 0

[profile.dev.package."*"]
opt-level = 0
incremental = true

[profile.dev.build-override]
opt-level = 0
incremental = true
